name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ##  Quick Checklist
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.

        ✅ I am using the **latest version of the Bag of Tricks**
        ✅ I have searched all issues here to see if this has already been reported 
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-expectation
    attributes:
      label: What's the expected result?
      description: Describe what you expect to happen.
    validations:
      required: true
  - type: input
    id: bug-reproduction
    attributes:
      label: Link to Minimal Reproducible Example
      description: '**A minimal reproduction is required** so that others can help debug your issue.'
      placeholder: 'https://github.com/you/your-minimal-repo'
    validations:
      required: true
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label:  I am willing to submit a pull request for this issue.
          required: false
