blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/vtbag/inspection-chamber/discussions
    about: Does the issue involve a lot of explanation, or are you not sure how it can be split into actionable tasks? Consider starting a discussion first.
